### ISSUE TITLE
The Action fails with "Could not setup Developer Command Prompt"

### ISSUE THREAD

**Issue by exarkun** [ilammy/msvc-dev-cmd#1]
Attempting to use the action like this:

```
name: Python package
on: [push]
jobs:
  build:
    runs-on: "windows-latest"
    strategy:
      matrix:
        python-version:
          - "2.7"
    steps:
    - uses: ilammy/msvc-dev-cmd@v1
```

results in a failure:

```
##[error]Could not setup Developer Command Prompt
##[error]Node run failed with exit code 1
```

**Comment by ilammy** [comment]
Hm... I admit this action was not maintained well. For example, it lacked scheduled builds to verify that it's still working, and lacked ‘integration’ testing of the released versions. I’ll add those shortly to be notified about any breakage in the future. (Though, given how simple it is, this action unlikely to seriously break.)

Now... it’s really strange that you see it failing. I‘d expect some environment change and bit rot, or the influence of Python 2.7 which was recently EOLed. But that does not seem to be the case. I’ve checked the exact workflow that you provided too and [it seems to work fine](https://github.com/ilammy/msvc-dev-cmd/actions/runs/37819990).

Could you please link a repo that fails the build? Enabled debug logging may also help: you need to define an Action secret named `ACTIONS_STEP_DEBUG` to enable it.

**Comment by exarkun** [comment]
Hi.  Thanks for the quick reply!

The project where I'm trying to use this action is https://github.com/LeastAuthority/magic-folder and there is an open PR that introduces the usage at https://github.com/LeastAuthority/magic-folder/pull/18.

Looking through the revisions to find the best workflow run demonstrating the issue, I see I might have over-simplified the example in the issue description here.

https://github.com/LeastAuthority/magic-folder/runs/438948109 is a workflow run using a configuration closest to what I posted above and where the step succeeded.

The problem actually came up when I tried to choose a specific version.  https://github.com/LeastAuthority/magic-folder/blob/321796bd068af1f1729cd1a3aedcd75d9216ca80/.github/workflows/pythonpackage.yml produced the failure I described above, visible at https://github.com/LeastAuthority/magic-folder/runs/438969918.

I'll try enabling debug logging and see if that reveals anything interesting.  Sorry about the initially incorrect report.

**Comment by exarkun** [comment]
Here's the debug logging:

```
##[debug]Evaluating condition for step: 'Run ilammy/msvc-dev-cmd@v1'
##[debug]Parsing expression: <success()>
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Run ilammy/msvc-dev-cmd@v1
##[debug]Loading inputs
##[debug]Loading env
Run ilammy/msvc-dev-cmd@v1
##[debug]Arguments: x64 -vcvars_ver=9
##[debug]Writing helper file: C:\Users\runneradmin\msvc-dev-cmd.bat
##[debug]Executing helper
##[debug]Helper failed: Command failed: cmd.exe /q /c C:\Users\runneradmin\msvc-dev-cmd.bat
##[debug]
##[debug]Removing helper
##[error]Could not setup Developer Command Prompt
##[error]Node run failed with exit code 1
##[debug]Finishing: Run ilammy/msvc-dev-cmd@v1
```

For this configuration:
```
name: Python package

on: [push]

jobs:
  build:

    runs-on: "windows-latest"
    strategy:
      matrix:
        python-version:
          - "2.7"

    steps:
    - uses: actions/checkout@v2
    # Get MS VC++ 9                                                                                                                                                                           
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        toolset: "9"
```

**Comment by exarkun** [comment]
If I change the configuration to pick a newer version of the toolset, eg `toolset: "14.0"`, then it succeeds. :/

Is the problem that 9.0 (Visual Studio 2008) is too old and not supported?

**Comment by exarkun** [comment]
Maybe I misunderstood what this action is for.  Looking at the debug output and some of the code, it looks like it is not for installing Visual Studio.  Instead, it is for activating one of the existing installations that is already included in the GitHub Windows environment.  Is that right?

**Comment by ilammy** [comment]
Oh!.. Yeah... You are right: this action is just a thin wrapper over Visual Studio's batch file. It can only activate the environment already included in GitHub Action runner. It does not install the specified toolset version, like some other actions do (e.g., `actions-rs/toolchain` for Rust toolchains).

Well, that’s mostly because I have no clue how to properly download and install Visual Studio from a script. For some reason I doubt it can be automated easily, especially for older ones. I’m also not aware of actions that do that, sadly.

**Comment by matjue85** [comment]
> Attempting to use the action like this:
> 
> ```
> name: Python package
> on: [push]
> jobs:
>   build:
>     runs-on: "windows-latest"
>     strategy:
>       matrix:
>         python-version:
>           - "2.7"
>     steps:
>     - uses: ilammy/msvc-dev-cmd@v1
> ```
> 
> results in a failure:
> 
> ```
> ##[error]Could not setup Developer Command Prompt
> ##[error]Node run failed with exit code 1
> ```

**Comment by ajfriend** [comment]
It looks like I had the same problem (compiling for python 2.7), but was able to solve it with the following:

```yml
- name: Add msbuild to PATH
  uses: microsoft/setup-msbuild@v1.0.0
    with:
      vs-version: [9.0]

- uses: ilammy/msvc-dev-cmd@v1.2.0
  with:
    toolset: 9.0
```

@ilammy, it looks like `microsoft/setup-msbuild` would solve the issue you mentioned around installing Visual Studio from a script.

**Comment by ajfriend** [comment]
Actually, that didn't work; it just failed silently.

It seems like i can install msbuild ok with

```yml
- name: Add msbuild to PATH
  uses: microsoft/setup-msbuild@v1.0.0
  with:
    vs-version: 9.0
```

but I get an error on:

```yml
- uses: ilammy/msvc-dev-cmd@v1.2.0
  with:
    toolset: 9.0
```

@ilammy, would you be able to support 9.0 for building python 2.7 packages?
