### ISSUE TITLE
Surprising Time Spent on Running msvc-dev-cmd@v1 on windows-latest

### ISSUE THREAD

**Issue by davecom** [ilammy/msvc-dev-cmd#12]
I'm suddenly seeing repositories take over 4 minutes on running msvc-dev-cmd@v1, while just a couple days ago they were taking less than a minute. What variables could be causing the increased time? Is there something I can tweak? Does it have to do with changes to windows-latest? Thanks in advance for any insight.

Below is our yml file and the step that is becoming perversely long is "Setup Developer Command Prompt"

```
name: Build and Test

on:
  push

jobs:

  build-and-test-windows:
    name: Build and Test on Windows
    runs-on: windows-latest
    timeout-minutes: 5

    steps:
      - name: Setup Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
      - name: Check Out Source Code
        uses: actions/checkout@v2
      - name: nmake Build
        run: nmake
      - name: Run Executable
        run: .\assignment4.exe

  build-and-test-linux:
    name: Build and Test on Linux
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Check Out Source Code
        uses: actions/checkout@v2
      - name: GNU make Build
        run: make
      - name: Run Executable
        run: ./assignment4
```
