### ISSUE TITLE
VisualStudioVersion is not set

### ISSUE THREAD

**Issue by theseankelly** [ilammy/msvc-dev-cmd#2]
First off -- thanks for the hard work and contribution!

I'm working on a custom pipeline -- the build step of my project uses a tool which must be run in the context of a VS dev prompt and relies on the variable `VisualStudioVersion`.

Here's a stripped down version of my pipeline:
```
jobs:
  build:
    runs-on: windows-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1.0.1
    - name: Build ament source
      run: colcon build --merge-install --cmake-args -A x64
      working-directory: ./dev/ament
      shell: cmd
```

The `colcon build` command reports `VisualStudioVersion is not set, please run within a Visual Studio Command Prompt.`

I'm really new to GitHub actions so this very well could be user error. I've read some things about needing to explicity export environment variables to pipelines or does your extension take care of this?
