### ISSUE TITLE
Build opencv failed use v14.0 toolset

### ISSUE THREAD

**Issue by waruqi** [ilammy/msvc-dev-cmd#46]
```
       - uses: ilammy/msvc-dev-cmd@v1
         with:
          arch: ${{ matrix.arch }}
          toolset: 14.0
```

https://github.com/xmake-mirror/build-artifacts/runs/3065402363?check_suite_focus=true

> 67>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB6001: Invalid command line switch for "cmd.exe". System.ArgumentException: Item has already been added. Key in dictionary: 'WINDOWSSDKVERSION'  Key being added: 'WindowsSDKVersion' [C:\Users\runneradmin\AppData\Local\.xmake\cache\packages\2107\o\opencv\4.5.2\source\opencv-4.5.2\build\ZERO_CHECK.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB6001:    at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
