### ISSUE TITLE
Specify exact version number rather than latest

### ISSUE THREAD

**Issue by SSoelvsten** [ilammy/msvc-dev-cmd#68]
I am on https://github.com/thomasmoelhave/tpie/pull/257 , adding CI for all major platforms for the TPIE library which my research project is heavily dependent upon. Yet, due to a very weird error (that should be independently fixed of this CI pull request), the library cannot compile with the latest 2019 MSC compiler, but only up to 19.27.

Specifically, as far as I can tell, the TPIE compatibility with MSC breaks between these two version numbers

|                                    | Working       | Failing           |
|-----------------------------|-------------------|-------------------|
| Product Version      | 16.7               | 16.8.1            |
| Runtime Library     | 14.27             | 14.28             |
| MSC version            | 19.27.29112 | 19.28.29333 |

Based on the README I am unable to figure out what value to parse to this GitHub Action? There is a `toolset` argument, but I seem to get an error regardless of whether I set it to *16.7*, *14.27* or *19.27* (or maybe I missed a specific value when trying it out?).

**Comment by SSoelvsten** [comment]
Maybe all this boils down to "*How do I derive the toolset number?*" which in itself might be worth adding to the README.

**Comment by pzhlkj6612** [comment]
Hi! I've not dug into the issues you link but still want to share something with you.

I've tested GitHub Actions with the following workflow file:

```YAML
name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, windows-2022]
        toolset_ver:
          - "v140"
          - "v141"
          - 140
          - 141
          - 14
          - "14.0"
          - 14.1
          - 14.2
          - 14.21
          - 14.22
          - 14.23
          - 14.24
          - 14.25
          - 14.26
          - 14.27
          - 14.28
          - 14.29
          - "14.30"
          - 14.3
          - 14.31
          - 14.32
          - 14.33
          - 14.34
          - 14.35
          - 14.36
          - 14.37
          - 14.38
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
          toolset: ${{ matrix.toolset_ver }}
      # https://learn.microsoft.com/cpp/build/reference/help-compiler-command-line-help
      - run: |
          "CL_VERSION=$(cl /? 2>&1 | Select-String -Pattern 'Compiler Version' -CaseSensitive -SimpleMatch)" | Out-File -Append -FilePath ${env:\GITHUB_OUTPUT}
        shell: pwsh
        id: cl
      - run: echo '::warning ::${{ matrix.os }} + toolset-${{ matrix.toolset_ver }} = ${{ steps.cl.outputs.CL_VERSION }}'

```

The result is:

<table>
<thead>
  <tr>
    <th>toolset</th>
    <th>windows-2019</th>
    <th>windows-2022</th>
    <th>note</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td>14</td>
    <td>19.29.30152</td>
    <td>19.37.32824</td>
    <td></td>
  </tr>
  <tr>
    <td>14.0</td>
    <td>19.00.24247.2</td>
    <td></td>
    <td>140</td>
  </tr>
  <tr>
    <td>14.1</td>
    <td>19.16.27051</td>
    <td>19.16.27051</td>
    <td>v141</td>
  </tr>
  <tr>
    <td>14.2</td>
    <td>19.29.30152</td>
    <td>19.29.30152</td>
    <td></td>
  </tr>
  <tr>
    <td>14.25</td>
    <td>19.25.28614</td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>14.29</td>
    <td>19.29.30152</td>
    <td>19.29.30152</td>
    <td></td>
  </tr>
  <tr>
    <td>14.3</td>
    <td></td>
    <td>19.37.32824</td>
    <td></td>
  </tr>
  <tr>
    <td>14.35</td>
    <td></td>
    <td>19.35.32217.1</td>
    <td></td>
  </tr>
  <tr>
    <td>14.37</td>
    <td></td>
    <td>19.37.32824</td>
    <td></td>
  </tr>
</tbody>
</table>

(The above table is generated by [TablesGenerator.com](https://www.tablesgenerator.com/html_tables))

The versions of toolset are from the "windowsNNNN-readme.md" files in https://github.com/actions/runner-images/tree/main/images/win . Please search "Microsoft.VisualStudio.Component.VC" in those files.
