### ISSUE TITLE
with:     vsversion: 2019     toolset: 14.4  fails on windows2019-runner

### ISSUE THREAD

**Issue by JoergAtGithub** [ilammy/msvc-dev-cmd#91]
GitHubs Windows2019-Runner-Image contains the toolset 14.4 but only VS2019: https://github.com/actions/runner-images/blob/win22/20240603.1/images/windows/Windows2019-Readme.md

This argument combination
  ```
uses: ilammy/msvc-dev-cmd@v1
        with:
          vsversion: 2019
          toolset: 14.4
```
fails, because msvc-dev-cmd looks in the 2019 path for the 14.4 toolset.

**Comment by pzhlkj6612** [comment]
Hi. Although I don't think I fully understand what you wrote, I can guess what you were encountering. Do you want to use VS 2019? If so:

```YAML
    uses: ilammy/msvc-dev-cmd@v1
      with:
        vsversion: 2019

```

We were going to have some explanation about the "toolset" argument in README, but unfortunately that has been aborted (PR #89).
